### PR TITLE
some more feature and dark mode .

### LINKED ISSUE #6: add dark mode

### PR DESCRIPTION
**Pull request by sourabhsharma24**
Resolves #6.

### CODE REVIEW

**Review by prabhat7k — COMMENTED** [review]
Dark mode doesn't work on analog clock

**Comment by prabhat7k** [comment]
show the preview of the page

**Comment by sourabh1111111** [comment]
> show the preview of the page

Screenshot (158)
Screenshot (159)

**Comment by sourabhsharma24** [comment]
> show the preview of the page


Screenshot (158)
Screenshot (159)

**Comment by prabhat7k** [comment]
clock and text are too bright to be in dark mode

**Pull request closed without merging**
